version: "3.8"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=Ch35t3r!
    volumes:
      - ./config:/config                  # code-server config + extensions
      - /home/pi/my_python_project:/config/workspace  # your project folder
    ports:
      - "8443:8080"
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "apk add --no-cache python3 py3-pip && /init"
